#Create PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: k8s-slave0
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-k8s-0-test-pool-1-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "1073741824"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-test-pool-1-0
    namespace: myminio
  hostPath:
    path: /opt/local-path-provisioner/pvc-myminio_0-test-pool-1-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-slave0
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: k8s-slave1
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-k8s-0-test-pool-1-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "1073741824"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-test-pool-1-1
    namespace: myminio
  hostPath:
    path: /opt/local-path-provisioner/pvc-myminio_0-test-pool-1-1
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-slave1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: k8s-slave2
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-k8s-0-test-pool-1-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "1073741824"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-test-pool-1-2
    namespace: myminio
  hostPath:
    path: /opt/local-path-provisioner/pvc-myminio_0-test-pool-1-2
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-slave2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: k8s-slave3
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-k8s-0-test-pool-1-3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "1073741824"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-test-pool-1-3
    namespace: myminio
  hostPath:
    path: /opt/local-path-provisioner/pvc-myminio_0-test-pool-1-3
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-slave3
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: k8s-slave0
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-k8s-0-test-pool-0-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "1073741824"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-test-pool-0-0
    namespace: myminio
  hostPath:
    path: /opt/local-path-provisioner/pvc-myminio_0-test-pool-0-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-slave0
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: k8s-slave1
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-k8s-0-test-pool-0-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "1073741824"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-test-pool-0-1
    namespace: myminio
  hostPath:
    path: /opt/local-path-provisioner/pvc-myminio_0-test-pool-0-1
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-slave1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: k8s-slave2
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-k8s-0-test-pool-0-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "1073741824"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-test-pool-0-2
    namespace: myminio
  hostPath:
    path: /opt/local-path-provisioner/pvc-myminio_0-test-pool-0-2
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-slave2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: k8s-slave3
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-k8s-0-test-pool-0-3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "1073741824"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: 0-test-pool-0-3
    namespace: myminio
  hostPath:
    path: /opt/local-path-provisioner/pvc-myminio_0-test-pool-0-3
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-slave3
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem