Create PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k8s-slave0
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    v1.min.io/console: test-console
    v1.min.io/pool: pool-1
    v1.min.io/tenant: test
  name: 0-test-pool-1-0
  namespace: myminio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1073741824"
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-k8s-data1-test-pool-1-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k8s-slave1
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    v1.min.io/console: test-console
    v1.min.io/pool: pool-1
    v1.min.io/tenant: test
  name: 0-test-pool-1-1
  namespace: myminio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1073741824"
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-k8s-data1-test-pool-1-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k8s-slave2
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    v1.min.io/console: test-console
    v1.min.io/pool: pool-1
    v1.min.io/tenant: test
  name: 0-test-pool-1-2
  namespace: myminio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1073741824"
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-k8s-data1-test-pool-1-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k8s-slave3
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    v1.min.io/console: test-console
    v1.min.io/pool: pool-1
    v1.min.io/tenant: test
  name: 0-test-pool-1-3
  namespace: myminio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1073741824"
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-k8s-data1-test-pool-1-3